const gamesData = [
  {
    "name": "7 Wonders",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 7,
    "minplaytime": 30,
    "maxplaytime": 30,
    "year": "2011",
    "language_dependence": "No necessary in-game text",
    "age": "10+",
    "best_players": "4,5",
    "expansions": [
      {
        "name": "7 Wonders Duel: Pantheon",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 2,
        "minplaytime": 30,
        "maxplaytime": 30,
        "year": "2016",
        "language_dependence": "No necessary in-game text",
        "age": "10+",
        "best_players": "2"
      },
      {
        "name": "7 Wonders: Cities",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 8,
        "minplaytime": 40,
        "maxplaytime": 40,
        "year": "2012",
        "language_dependence": "No necessary in-game text",
        "age": "10+",
        "best_players": "4,5"
      }
    ]
  },
  {
    "name": "7 Wonders Duel",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 2,
    "minplaytime": 30,
    "maxplaytime": 30,
    "year": "2016",
    "language_dependence": "No necessary in-game text",
    "age": "10+",
    "best_players": "2",
    "expansions": []
  },
  {
    "name": "ASTER",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 0,
    "maxplaytime": 0,
    "year": "2021",
    "language_dependence": "",
    "age": "",
    "best_players": "",
    "expansions": []
  },
  {
    "name": "Avalon: Big Box",
    "itemtype": "standalone",
    "minplayers": 5,
    "maxplayers": 10,
    "minplaytime": 30,
    "maxplaytime": 30,
    "year": "2022",
    "language_dependence": "Some necessary text - easily memorized or small crib sheet",
    "age": "12+",
    "best_players": "7,8",
    "expansions": []
  },
  {
    "name": "BANG! La Pallottola!",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 8,
    "minplaytime": 20,
    "maxplaytime": 40,
    "year": "2009",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "8+",
    "best_players": "6,7",
    "expansions": []
  },
  {
    "name": "Black Forest",
    "itemtype": "standalone",
    "minplayers": 1,
    "maxplayers": 4,
    "minplaytime": 60,
    "maxplaytime": 120,
    "year": "2025",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "12+",
    "best_players": "3",
    "expansions": []
  },
  {
    "name": "Bonsai",
    "itemtype": "standalone",
    "minplayers": 1,
    "maxplayers": 4,
    "minplaytime": 40,
    "maxplaytime": 40,
    "year": "2023",
    "language_dependence": "No necessary in-game text",
    "age": "8+",
    "best_players": "3",
    "expansions": [
      {
        "name": "Bonsai: Wabi Sabi",
        "itemtype": "expansion",
        "minplayers": 1,
        "maxplayers": 5,
        "minplaytime": 40,
        "maxplaytime": 40,
        "year": "2024",
        "language_dependence": "",
        "age": "8",
        "best_players": "4,5"
      }
    ]
  },
  {
    "name": "Il Buono, il Brutto e il Munchkin",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2012",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "10+",
    "best_players": "4,5",
    "expansions": []
  },
  {
    "name": "Callisto",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 15,
    "maxplaytime": 30,
    "year": "2016",
    "language_dependence": "No necessary in-game text",
    "age": "6+",
    "best_players": "2",
    "expansions": []
  },
  {
    "name": "Carcassonne",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 5,
    "minplaytime": 30,
    "maxplaytime": 45,
    "year": "2000",
    "language_dependence": "No necessary in-game text",
    "age": "8+",
    "best_players": "2",
    "expansions": [
      {
        "name": "Carcassonne: Abbazie e Borgomastri",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 30,
        "maxplaytime": 30,
        "year": "2010",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "3"
      },
      {
        "name": "Carcassonne: Bazar, Ponti e Castelli",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 30,
        "maxplaytime": 45,
        "year": "2010",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "3,4"
      },
      {
        "name": "Carcassonne: Commercianti e Costruttori",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 60,
        "maxplaytime": 60,
        "year": "2010",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "2,3"
      },
      {
        "name": "Carcassonne: Espansione 10 \u2013 Il Circo",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 45,
        "maxplaytime": 45,
        "year": "2018",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "3"
      },
      {
        "name": "Carcassonne: Il Conte, il Re e l'Eretico",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 30,
        "maxplaytime": 45,
        "year": "2011",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "3"
      },
      {
        "name": "Carcassonne: La Catapulta",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 30,
        "maxplaytime": 45,
        "year": "2008",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "2"
      },
      {
        "name": "Carcassonne: La Principessa e il Drago",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 60,
        "maxplaytime": 60,
        "year": "2010",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "3,4"
      },
      {
        "name": "Carcassonne: La Torre",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 60,
        "maxplaytime": 60,
        "year": "2010",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "3"
      },
      {
        "name": "Carcassonne: Le Ali",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 0,
        "maxplaytime": 0,
        "year": "2012",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "2,3"
      },
      {
        "name": "Carcassonne: Locande & Cattedrali",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 60,
        "maxplaytime": 60,
        "year": "2010",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "2,3"
      },
      {
        "name": "Carcassonne: Pecore e Colline",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 40,
        "maxplaytime": 40,
        "year": "2014",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "2,3,4"
      }
    ]
  },
  {
    "name": "Le Case della Follia: Seconda Edizione",
    "itemtype": "standalone",
    "minplayers": 1,
    "maxplayers": 5,
    "minplaytime": 120,
    "maxplaytime": 180,
    "year": "2016",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "3,4",
    "expansions": []
  },
  {
    "name": "Catan: Il Gioco",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 4,
    "minplaytime": 60,
    "maxplaytime": 120,
    "year": "2016",
    "language_dependence": "Some necessary text - easily memorized or small crib sheet",
    "age": "8+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Citadels",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 8,
    "minplaytime": 20,
    "maxplaytime": 60,
    "year": "2013",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "10+",
    "best_players": "5",
    "expansions": []
  },
  {
    "name": "Cluedo",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 6,
    "minplaytime": 40,
    "maxplaytime": 40,
    "year": "2012",
    "language_dependence": "Some necessary text - easily memorized or small crib sheet",
    "age": "8+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Dominion (Seconda Edizione)",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 30,
    "maxplaytime": 30,
    "year": "2021",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "8+",
    "best_players": "2,3",
    "expansions": []
  },
  {
    "name": "Dorfromantik: Sakura",
    "itemtype": "standalone",
    "minplayers": 1,
    "maxplayers": 6,
    "minplaytime": 30,
    "maxplaytime": 90,
    "year": "2025",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "8+",
    "best_players": "2",
    "expansions": []
  },
  {
    "name": "Everdell: Collector's Edition",
    "itemtype": "standalone",
    "minplayers": 1,
    "maxplayers": 4,
    "minplaytime": 40,
    "maxplaytime": 80,
    "year": "2019",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "10+",
    "best_players": "3",
    "expansions": []
  },
  {
    "name": "Exploding Kittens",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 5,
    "minplaytime": 15,
    "maxplaytime": 15,
    "year": "2017",
    "language_dependence": "Some necessary text - easily memorized or small crib sheet",
    "age": "8+",
    "best_players": "4,5",
    "expansions": []
  },
  {
    "name": "Exploding Kittens: Edizione VM18",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 5,
    "minplaytime": 10,
    "maxplaytime": 20,
    "year": "2018",
    "language_dependence": "Some necessary text - easily memorized or small crib sheet",
    "age": "14+",
    "best_players": "4,5",
    "expansions": []
  },
  {
    "name": "futuRisiKo!",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 180,
    "maxplaytime": 180,
    "year": "2012",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "12+",
    "best_players": "4,5,6",
    "expansions": []
  },
  {
    "name": "Harmonies",
    "itemtype": "standalone",
    "minplayers": 1,
    "maxplayers": 4,
    "minplaytime": 30,
    "maxplaytime": 45,
    "year": "2024",
    "language_dependence": "No necessary in-game text",
    "age": "8+",
    "best_players": "2,3",
    "expansions": []
  },
  {
    "name": "HeroQuest",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 5,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2022",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "8+",
    "best_players": "5",
    "expansions": [
      {
        "name": "HeroQuest: la maga dello specchio",
        "itemtype": "expansion",
        "minplayers": 1,
        "maxplayers": 5,
        "minplaytime": 30,
        "maxplaytime": 120,
        "year": "2023",
        "language_dependence": "",
        "age": "",
        "best_players": ""
      }
    ]
  },
  {
    "name": "Illuminati",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 6,
    "minplaytime": 60,
    "maxplaytime": 180,
    "year": "2014",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Kingdomino",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 15,
    "maxplaytime": 25,
    "year": "2021",
    "language_dependence": "No necessary in-game text",
    "age": "6+",
    "best_players": "2,4",
    "expansions": []
  },
  {
    "name": "Lancillotto",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 60,
    "maxplaytime": 90,
    "year": "2017",
    "language_dependence": "No necessary in-game text",
    "age": "Up to 14",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Marvel Zombies: Un Gioco Zombicide",
    "itemtype": "standalone",
    "minplayers": 1,
    "maxplayers": 6,
    "minplaytime": 60,
    "maxplaytime": 60,
    "year": "2022",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "10+",
    "best_players": "2,4",
    "expansions": []
  },
  {
    "name": "Munchkin",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 60,
    "maxplaytime": 120,
    "year": "2015",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "10+",
    "best_players": "4",
    "expansions": [
      {
        "name": "Munchkin 2/3: L'Ascia o Raddoppia",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 6,
        "minplaytime": 60,
        "maxplaytime": 60,
        "year": "2004",
        "language_dependence": "Extensive use of text - massive conversion needed to be playable",
        "age": "",
        "best_players": ""
      },
      {
        "name": "Munchkin 4: Destri Destrieri",
        "itemtype": "expansion",
        "minplayers": 3,
        "maxplayers": 6,
        "minplaytime": 90,
        "maxplaytime": 90,
        "year": "2005",
        "language_dependence": "Extensive use of text - massive conversion needed to be playable",
        "age": "12+",
        "best_players": "4,5"
      },
      {
        "name": "Munchkin 5, 6 e 7: Tutti i Mostri Fatti a Fette",
        "itemtype": "expansion",
        "minplayers": 3,
        "maxplayers": 6,
        "minplaytime": 60,
        "maxplaytime": 60,
        "year": "2013",
        "language_dependence": "Extensive use of text - massive conversion needed to be playable",
        "age": "",
        "best_players": ""
      }
    ]
  },
  {
    "name": "Munchkin Apocalisse",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2012",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "10+",
    "best_players": "4,5",
    "expansions": []
  },
  {
    "name": "Munchkin Conan",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2014",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Munchkin Cthulhu",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2008",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Munchkin dei Caraibi",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2009",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "4,5",
    "expansions": []
  },
  {
    "name": "Munchkin Fu",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2007",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "10+",
    "best_players": "4,5",
    "expansions": []
  },
  {
    "name": "Munchkin Leggende",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 60,
    "maxplaytime": 120,
    "year": "2013",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "8+",
    "best_players": "3",
    "expansions": []
  },
  {
    "name": "Munchkin Morde!",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2007",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "4,5",
    "expansions": []
  },
  {
    "name": "Munchkin Oz",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 60,
    "maxplaytime": 120,
    "year": "2015",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "8+",
    "best_players": "4,5",
    "expansions": []
  },
  {
    "name": "Munchkin Quest",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 180,
    "maxplaytime": 180,
    "year": "2010",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Munchkin Zombi",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2011",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "10+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "My Shelfie",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 30,
    "maxplaytime": 30,
    "year": "2022",
    "language_dependence": "No necessary in-game text",
    "age": "8+",
    "best_players": "2",
    "expansions": []
  },
  {
    "name": "Mysterium",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 7,
    "minplaytime": 42,
    "maxplaytime": 42,
    "year": "2019",
    "language_dependence": "No necessary in-game text",
    "age": "8+",
    "best_players": "5,6",
    "expansions": [
      {
        "name": "Mysterium: Segni Nascosti",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 7,
        "minplaytime": 42,
        "maxplaytime": 42,
        "year": "2019",
        "language_dependence": "No necessary in-game text",
        "age": "8+",
        "best_players": "5,6,7"
      },
      {
        "name": "Mysterium: Segreti e Bugie",
        "itemtype": "expansion",
        "minplayers": 2,
        "maxplayers": 7,
        "minplaytime": 42,
        "maxplaytime": 42,
        "year": "2019",
        "language_dependence": "No necessary in-game text",
        "age": "10+",
        "best_players": "4,5"
      }
    ]
  },
  {
    "name": "Orlog: Assassin's Creed Valhalla Dice Game",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 2,
    "minplaytime": 10,
    "maxplaytime": 30,
    "year": "2021",
    "language_dependence": "Some necessary text - easily memorized or small crib sheet",
    "age": "10+",
    "best_players": "2",
    "expansions": []
  },
  {
    "name": "The Others",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 5,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2016",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "5",
    "expansions": []
  },
  {
    "name": "Pandemic Legacy: Season 1",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 60,
    "maxplaytime": 60,
    "year": "2015",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Pandemic Legacy: Season 2",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 60,
    "maxplaytime": 60,
    "year": "2017",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Pusher's Street",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 5,
    "minplaytime": 60,
    "maxplaytime": 120,
    "year": "2007",
    "language_dependence": "",
    "age": "18",
    "best_players": "",
    "expansions": []
  },
  {
    "name": "Quantum",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 60,
    "maxplaytime": 60,
    "year": "2014",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "10+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Quarto Mini",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 2,
    "minplaytime": 20,
    "maxplaytime": 20,
    "year": "2014",
    "language_dependence": "No necessary in-game text",
    "age": "8+",
    "best_players": "2",
    "expansions": []
  },
  {
    "name": "RisiKo!",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 60,
    "maxplaytime": 60,
    "year": "2017",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "10+",
    "best_players": "4,5,6",
    "expansions": []
  },
  {
    "name": "Risiko!: Batman \u2013 La Caduta Di Gotham City",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 4,
    "minplaytime": 60,
    "maxplaytime": 60,
    "year": "2021",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "",
    "best_players": "",
    "expansions": []
  },
  {
    "name": "Rising Sun",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 5,
    "minplaytime": 90,
    "maxplaytime": 120,
    "year": "2018",
    "language_dependence": "Some necessary text - easily memorized or small crib sheet",
    "age": "14+",
    "best_players": "4,5",
    "expansions": []
  },
  {
    "name": "Saint Seiya: I Cavalieri dello Zodiaco \u2013 Deckbuilding",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 5,
    "minplaytime": 40,
    "maxplaytime": 60,
    "year": "2019",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "8+",
    "best_players": "3",
    "expansions": []
  },
  {
    "name": "Scrabble: L'originale in Italiano",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2012",
    "language_dependence": "Unplayable in another language",
    "age": "10+",
    "best_players": "2",
    "expansions": []
  },
  {
    "name": "Si, Oscuro Signore!",
    "itemtype": "standalone",
    "minplayers": 4,
    "maxplayers": 16,
    "minplaytime": 20,
    "maxplaytime": 30,
    "year": "2014",
    "language_dependence": "Some necessary text - easily memorized or small crib sheet",
    "age": "10+",
    "best_players": "6,8",
    "expansions": []
  },
  {
    "name": "Il Signore degli Anelli: Duel for Middle-earth",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 2,
    "minplaytime": 30,
    "maxplaytime": 30,
    "year": "2024",
    "language_dependence": "No necessary in-game text",
    "age": "10+",
    "best_players": "2",
    "expansions": []
  },
  {
    "name": "Star Munchkin",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2008",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Su Una Scala da 1 a T-Rex",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 8,
    "minplaytime": 15,
    "maxplaytime": 15,
    "year": "2021",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "6+",
    "best_players": "6",
    "expansions": []
  },
  {
    "name": "Ticket to Ride: Europa",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 5,
    "minplaytime": 30,
    "maxplaytime": 60,
    "year": "2013",
    "language_dependence": "No necessary in-game text",
    "age": "8+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Il Trauma del Tram",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 13,
    "minplaytime": 30,
    "maxplaytime": 90,
    "year": "2020",
    "language_dependence": "Unplayable in another language",
    "age": "16+",
    "best_players": "5,7",
    "expansions": []
  },
  {
    "name": "Tre Draghi al Buio",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 6,
    "minplaytime": 30,
    "maxplaytime": 30,
    "year": "2020",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "",
    "best_players": "3,4,5",
    "expansions": []
  },
  {
    "name": "Il Trono di Spade: Il Gioco da Tavolo Seconda Edizione",
    "itemtype": "standalone",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 120,
    "maxplaytime": 240,
    "year": "2012",
    "language_dependence": "Some necessary text - easily memorized or small crib sheet",
    "age": "14+",
    "best_players": "6",
    "expansions": []
  },
  {
    "name": "UNO",
    "itemtype": "standalone",
    "minplayers": 2,
    "maxplayers": 10,
    "minplaytime": 30,
    "maxplaytime": 30,
    "year": "2019",
    "language_dependence": "No necessary in-game text",
    "age": "5+",
    "best_players": "4,5,6",
    "expansions": []
  },
  {
    "name": "Vast: Le Caverne di Cristallo",
    "itemtype": "standalone",
    "minplayers": 1,
    "maxplayers": 5,
    "minplaytime": 75,
    "maxplaytime": 150,
    "year": "2018",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "4",
    "expansions": []
  },
  {
    "name": "Zombicide: 2a Edizione",
    "itemtype": "standalone",
    "minplayers": 1,
    "maxplayers": 6,
    "minplaytime": 60,
    "maxplaytime": 60,
    "year": "2021",
    "language_dependence": "Some necessary text - easily memorized or small crib sheet",
    "age": "10+",
    "best_players": "3",
    "expansions": []
  },
  {
    "name": "Dominion: Alchimia",
    "itemtype": "expansion",
    "minplayers": 2,
    "maxplayers": 4,
    "minplaytime": 30,
    "maxplaytime": 30,
    "year": "2010",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "10+",
    "best_players": "3",
    "expansions": []
  },
  {
    "name": "Munchkinomicon",
    "itemtype": "expansion",
    "minplayers": 3,
    "maxplayers": 6,
    "minplaytime": 90,
    "maxplaytime": 90,
    "year": "2011",
    "language_dependence": "Extensive use of text - massive conversion needed to be playable",
    "age": "12+",
    "best_players": "4,5",
    "expansions": []
  },
  {
    "name": "Il Trono di Spade: Il Gioco da Tavolo (Seconda Edizione) \u2013 La Madre dei Draghi",
    "itemtype": "expansion",
    "minplayers": 3,
    "maxplayers": 8,
    "minplaytime": 120,
    "maxplaytime": 240,
    "year": "2019",
    "language_dependence": "Moderate in-game text - needs crib sheet or paste ups",
    "age": "14+",
    "best_players": "6",
    "expansions": []
  }
];